region             = "ap-south-1"
vpc_name           = "pointcross-vpc"
vpc_cidr           = "10.0.0.0/16"
availability_zones = ["ap-south-1a", "ap-south-1b"]
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets    = ["10.0.3.0/24", "10.0.4.0/24"]
cluster_name       = "pointcross-eks-cluster"
desired_capacity   = 2
min_capacity       = 1
max_capacity       = 3
ecr_repo_name      = "nginx-app-repo"
