apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant2-quota
  namespace: tenant2
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
