apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: tenant2
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80 # Port inside the cluster
    targetPort: 80 # Port on the Pod
    nodePort: 30081 # Port exposed on Node IP (can be 30000–32767)
    protocol: TCP
