- name: Apply Namespace 1
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "/home/vbarask/assignment/Application-Deployment/namespace-1.yaml"

- name: Apply Namespace 2
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: "/home/vbarask/assignment/Application-Deployment/namespace-2.yaml"
